import os
import csv
import time
import random
from io import BytesIO

from PIL import Image
from google import genai
from google.genai import types



API_KEY = os.environ.get("GEMINI_API_KEY", "YOUR_API_KEY_HERE")

PROMPT_FILE = "prompt.txt"

MODEL_NAME = "gemini-2.5-flash-image"

ASPECT_RATIO = "16:9"

UPSCALE_FACTOR = 4

MAX_RETRIES = 6

INITIAL_RETRY_DELAY = 5

MAX_RETRY_DELAY = 90

SUCCESS_DELAY = 5



BASE_KEYWORDS = (
    "abstract, background, beautiful, beauty, bright, color, colorful, "
    "concept, creative, decoration, design, element, graphic, illustration, "
    "light, modern, nature, pattern, shape, space, style, texture, vibrant, "
    "wallpaper, art, digital, futuristic, glowing, gradient, geometric, "
    "layout, minimal, render, 3d, wave, dynamic, energy, flow, smooth"
)



try:
    client = genai.Client(api_key=API_KEY)

    print("✅ Google Gen AI client initialized.")

except Exception as e:

    print()
    print("❌ Failed to initialize Google Gen AI client.")
    print()
    print(f"{type(e).__name__}: {e}")
    print()

    raise SystemExit(1)



def get_unique_filename(filepath):
    """
    If the file exists, append (2), (3), etc. to the filename.
    Example: image.PNG -> image(2).PNG
    """
    if not os.path.exists(filepath):
        return filepath

    base, ext = os.path.splitext(filepath)
    counter = 2

    while True:
        new_filename = f"{base}({counter}){ext}"
        if not os.path.exists(new_filename):
            return new_filename
        counter += 1



def read_prompts_from_file(filename):

    if not os.path.exists(filename):
        print()
        print(f"❌ Error: '{filename}' was not found.")
        print("Create prompt.txt and put one prompt per line.")
        print()
        return []

    try:
        with open(filename, "r", encoding="utf-8") as file:
            prompts = []
            for line in file:
                line = line.strip()
                if line:
                    prompts.append(line)
        return prompts
    except Exception as e:
        print(f"❌ Error reading {filename}: {e}")
        return []



def is_rate_limit_error(error):

    error_text = str(error).lower()
    return (
        "429" in error_text
        or "resource_exhausted" in error_text
        or "resource exhausted" in error_text
        or "quota" in error_text
        or "rate limit" in error_text
    )



def generate_image(prompt):

    """
    Generate an image.
    Automatically retries temporary 429 errors
    using exponential backoff + jitter.
    """

    for attempt in range(1, MAX_RETRIES + 1):

        try:
            print(f"      API attempt {attempt}/{MAX_RETRIES}...")

            response = client.models.generate_content(
                model=MODEL_NAME,
                contents=prompt,
                config=types.GenerateContentConfig(
                    response_modalities=["IMAGE"],
                    image_config=types.ImageConfig(
                        aspect_ratio=ASPECT_RATIO
                    )
                )
            )

            for part in response.parts:
                if part.inline_data:
                    image_bytes = part.inline_data.data
                    if image_bytes:
                        return image_bytes

            raise RuntimeError("Google returned a response without image data.")

        except Exception as e:

            if is_rate_limit_error(e):
                if attempt >= MAX_RETRIES:
                    print()
                    print("      ❌ Maximum retry attempts reached.")
                    raise

                delay = min(
                    INITIAL_RETRY_DELAY * (2 ** (attempt - 1)),
                    MAX_RETRY_DELAY
                )

                jitter = random.uniform(0.5, 2.5)
                wait_time = delay + jitter

                print()
                print("      ⚠️ Google returned 429 RESOURCE_EXHAUSTED.")
                print(f"      Waiting {wait_time:.1f} seconds before retry...")

                time.sleep(wait_time)
                continue

            print()
            print(f"      ❌ API error: {type(e).__name__}: {e}")
            raise

    raise RuntimeError("Image generation failed.")



def upscale_image_4x(image_bytes):

    """
    Convert generated bytes to PIL image
    and enlarge 4x.
    """

    image = Image.open(BytesIO(image_bytes))

    if image.mode not in ("RGB", "RGBA"):
        image = image.convert("RGB")

    original_width, original_height = image.size
    new_width = original_width * UPSCALE_FACTOR
    new_height = original_height * UPSCALE_FACTOR

    print(f"      Original size: {original_width}x{original_height}")
    print(f"      4x size: {new_width}x{new_height}")

    image = image.resize(
        (new_width, new_height),
        Image.Resampling.LANCZOS
    )

    return image



def save_image(image, filename):

    if image.mode not in ("RGB", "RGBA"):
        image = image.convert("RGB")

    image.save(filename, "PNG", optimize=True)



def generate_images_from_prompts():

    adobe_data = []
    vecteezy_data = []
    dreamstime_data = []
    rf123_data = []

    prompts = read_prompts_from_file(PROMPT_FILE)
    total_images = len(prompts)

    if total_images == 0:
        print("❌ No prompts found.")
        return [], [], [], []

    print()
    print("=" * 70)
    print(f"Found {total_images} prompts in {PROMPT_FILE}")
    print(f"Model: {MODEL_NAME}")
    print(f"Aspect Ratio: {ASPECT_RATIO}")
    print(f"Upscale: {UPSCALE_FACTOR}x")
    print(f"Max Retries: {MAX_RETRIES}")
    print("=" * 70)
    print()

    for i, prompt in enumerate(prompts, start=1):

        print()
        print("=" * 70)
        print(f"[{i}/{total_images}] Processing")
        print("=" * 70)
        print()
        print("Prompt:")
        print(prompt)
        print()

        description = prompt.strip()
        if len(description) > 200:
            description = description[:197] + "..."

        base_filename = f"generated_image_{i}.PNG"
        final_filename = get_unique_filename(base_filename)

        try:
            print("🖼️ Generating image...")
            image_bytes = generate_image(prompt)
            print("      ✅ Image generated.")

            print("📐 Upscaling image 4x...")
            image = upscale_image_4x(image_bytes)

            print("💾 Saving PNG...")
            save_image(image, final_filename)
            print(f"      ✅ Saved: {final_filename}")

            adobe_data.append({
                "Filename": final_filename,
                "Title": description,
                "Keywords": BASE_KEYWORDS,
                "Category": "4",
                "Releases": ""
            })

            vecteezy_data.append({
                "Filename": final_filename,
                "Title": description,
                "Keywords": BASE_KEYWORDS
            })

            dreamstime_data.append({
                "Filename": final_filename,
                "Title": description,
                "Description": description,
                "Keywords": BASE_KEYWORDS
            })

            rf123_data.append({
                "Filename": final_filename,
                "Description": description,
                "Keywords": BASE_KEYWORDS
            })

            print("      ✅ Metadata added for all agencies.")

        except Exception as e:
            print()
            print(f"❌ Error generating image {i}:")
            print(f"      {type(e).__name__}: {e}")
            print()
            print("      Skipping this prompt.")

        if i < total_images:
            print(f"      Waiting {SUCCESS_DELAY}s...")
            time.sleep(SUCCESS_DELAY)

    return adobe_data, vecteezy_data, dreamstime_data, rf123_data



def write_csv_file(data, agency_name, headers):
    if not data:
        return

    filename = get_unique_filename(f"{agency_name}.csv")

    try:
        with open(filename, "w", newline="", encoding="utf-8-sig") as file:
            writer = csv.DictWriter(file, fieldnames=headers)
            writer.writeheader()
            writer.writerows(data)
        print(f"✅ {agency_name} CSV saved: {filename}")
    except Exception as e:
        print(f"❌ Failed to write {agency_name} CSV: {e}")


def write_adobe_csv(adobe_data):
    headers = ["Filename", "Title", "Keywords", "Category", "Releases"]
    write_csv_file(adobe_data, "Adobe", headers)

def write_vecteezy_csv(vecteezy_data):
    headers = ["Filename", "Title", "Keywords"]
    write_csv_file(vecteezy_data, "Vecteezy", headers)

def write_dreamstime_csv(dreamstime_data):
    headers = ["Filename", "Title", "Description", "Keywords"]
    write_csv_file(dreamstime_data, "Dreamstime", headers)

def write_123rf_csv(rf123_data):
    headers = ["Filename", "Description", "Keywords"]
    write_csv_file(rf123_data, "123RF", headers)



def main():

    print()
    print("=" * 70)
    print("          GOOGLE AI IMAGE GENERATOR")
    print("=" * 70)
    print()
    print(f"Model   : {MODEL_NAME}")
    print(f"Ratio   : {ASPECT_RATIO}")
    print(f"Upscale : {UPSCALE_FACTOR}x")
    print()

    adobe_data, vecteezy_data, dreamstime_data, rf123_data = generate_images_from_prompts()

    print()
    write_adobe_csv(adobe_data)
    write_vecteezy_csv(vecteezy_data)
    write_dreamstime_csv(dreamstime_data)
    write_123rf_csv(rf123_data)

    print()
    print("=" * 70)
    print("                    COMPLETE")
    print("=" * 70)
    print()
    print(f"Successful images: {len(adobe_data)}")
    print()
    print("✅ Process finished.")
    print()



if __name__ == "__main__":
    main()
